name = "flickrgroupaddr-api-cfworker"
type = "javascript"
zone_id = ""
account_id = ""
workers_dev = false
route = "api.flickrgroupaddr.com/api/v1/*"
compatibility_date = "2021-12-04"

# Environment vars
vars = { FGA_FLICKR_OAUTH_REQUEST_TOKEN_VERB = "GET", FGA_FLICKR_OAUTH_REQUEST_TOKEN_ENDPOINT_URI = "https://www.flickr.com/services/oauth/request_token", FGA_FLICKR_OAUTH_CALLBACK_URI = "https://auth.flickrgroupaddr.com/flickr/oauth/callback", FGA_FLICKR_OAUTH_SIGNATURE_METHOD = "HMAC-SHA1", FGA_FLICKR_OAUTH_VERSION="1.0" }

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
