name = "flickrgroupaddr-api-cfworker"
type = "javascript"
zone_id = ""
account_id = ""
workers_dev = false
route = "api.flickrgroupaddr.com/api/v1/*"
compatibility_date = "2021-12-04"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
